# Generated by Django 5.1.1 on 2024-09-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autorizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
